### PR TITLE
gallery styled ba Zsuzsa

### PR DESCRIPTION
**Pull request by ZsuzsaMano**
Went for a simple clear appearance. 
Removed a lot of unnecessary files like react logos.
Removed bootstrap. I would recommend removing it from solution_1. 
Added flex, shadow, and a font-style.

### CODE REVIEW

**Review by codeclassifiers — APPROVED** [review]

**Comment by codeclassifiers** [comment]
@ZsuzsaMano I have merged your PR. The suggestion to remove unnecessary files is surely useful since it will reduce overall size of the repository and overall page load time as well. I will remove the files from `solution_1` soon.
Also I have added relevant labels as per official Hacktoberfest guidelines to your PR.
Thank you for your contribution to this project

**Comment by codeclassifiers** [comment]
@all-contributors please add @ZsuzsaMano for adding `solution_3`

**Comment by codeclassifiers** [comment]
@all-contributors please add @ZsuzsaMano for adding solution_3 to this project

**Comment by ZsuzsaMano** [comment]
To remove unnecessary files, you could use my solution, and just remove the styles folder + link in HTML to stylesheet and google font.

**Pull request merged**
